baseURL = "https://haehet.github.io/"
languageCode = "en-us"
title = "haehet"
theme = "PaperMod"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowShareButtons = false
  ShowReadingTime = true
  ShowToc = true
  ShowCodeCopyButtons = true

  [params.profileMode]
    enabled = true
    title = "haehet"
    subtitle = "noob hacker"
    imageUrl = "/profile.jpeg"
    imageTitle = "profile"
    imageWidth = 160
    imageHeight = 160

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/haehet"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6
